### ISSUE TITLE
Safari cannot parse this JSON

### ISSUE THREAD

**Issue by janlelis** [palavatv/palava-client#15]
servers' joined_room event triggers this:

https://github.com/palavatv/palava-client/blob/v1.10.1/coffee/web_socket_channel.coffee#L34

**Comment by farao** [comment]
Could you paste the exact json string? maybe it's some character that it doesn't want to parse? the _?

**Comment by janlelis** [comment]
It's super strange, because when I manually parsed the JSON, Safari would not complain... I will try to retrieve and add more detailed debugging info

**Comment by janlelis** [comment]
Not an issue anymore in latest version
